run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

output:
  show-stats: true

linters-settings:
  govet:
    enable:
      - shadow
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - sloppyReassign
      - wrapperFunc
      - hugeParam
      - rangeValCopy
      - singleCaseSwitch
      - ifElseChain

linters:
  enable:
    - revive
    - govet
    - unconvert
    - staticcheck
    - unused
    - gosec
    - dupl
    - misspell
    - unparam
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - gocritic
    - nakedret
    - gosimple
    - prealloc
    - testifylint
    - paralleltest
  fast: false
  disable-all: true

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "should have a package comment"
      linters:
        - revive
    - path: _test\.go
      linters:
        - gosec
        - dupl
    - path: _test\.go
      text: "unused-parameter: parameter"
      linters:
        - revive
  exclude-use-default: false
