services:
  tg-reminder:
    image: mezk/tg-reminder:latest
    hostname: tg-reminder
    restart: always
    container_name: tg-reminder
    # Allow colorized output
    tty: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TZ=UTC
      - TELEGRAM_APITOKEN=${TELEGRAM_APITOKEN}
      - DEBUG=true
      - DB_FILE=/srv/db/data/tg-reminder.db
      - BACKUP_RETENTION=48h
      - BACKUP_INTERVAL=12h
      - BACKUP_DIR=/srv/db/data/backup
    volumes:
      - ./var/tg-reminder:/srv/db/data # mount volume with db file
