// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package notifier

import (
	"context"
	"github.com/mezk/tg-reminder/internal/pkg/domain"
	"sync"
)

// Ensure, that StorageMock does implement Storage.
// If this is not the case, regenerate this file with moq.
var _ Storage = &StorageMock{}

// StorageMock is a mock implementation of Storage.
//
//	func TestSomethingThatUsesStorage(t *testing.T) {
//
//		// make and configure a mocked Storage
//		mockedStorage := &StorageMock{
//			GetPendingRemindersFunc: func(ctx context.Context, limit int64) ([]domain.Reminder, error) {
//				panic("mock out the GetPendingReminders method")
//			},
//			UpdateReminderFunc: func(ctx context.Context, reminder domain.Reminder) error {
//				panic("mock out the UpdateReminder method")
//			},
//		}
//
//		// use mockedStorage in code that requires Storage
//		// and then make assertions.
//
//	}
type StorageMock struct {
	// GetPendingRemindersFunc mocks the GetPendingReminders method.
	GetPendingRemindersFunc func(ctx context.Context, limit int64) ([]domain.Reminder, error)

	// UpdateReminderFunc mocks the UpdateReminder method.
	UpdateReminderFunc func(ctx context.Context, reminder domain.Reminder) error

	// calls tracks calls to the methods.
	calls struct {
		// GetPendingReminders holds details about calls to the GetPendingReminders method.
		GetPendingReminders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int64
		}
		// UpdateReminder holds details about calls to the UpdateReminder method.
		UpdateReminder []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Reminder is the reminder argument value.
			Reminder domain.Reminder
		}
	}
	lockGetPendingReminders sync.RWMutex
	lockUpdateReminder      sync.RWMutex
}

// GetPendingReminders calls GetPendingRemindersFunc.
func (mock *StorageMock) GetPendingReminders(ctx context.Context, limit int64) ([]domain.Reminder, error) {
	if mock.GetPendingRemindersFunc == nil {
		panic("StorageMock.GetPendingRemindersFunc: method is nil but Storage.GetPendingReminders was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Limit int64
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockGetPendingReminders.Lock()
	mock.calls.GetPendingReminders = append(mock.calls.GetPendingReminders, callInfo)
	mock.lockGetPendingReminders.Unlock()
	return mock.GetPendingRemindersFunc(ctx, limit)
}

// GetPendingRemindersCalls gets all the calls that were made to GetPendingReminders.
// Check the length with:
//
//	len(mockedStorage.GetPendingRemindersCalls())
func (mock *StorageMock) GetPendingRemindersCalls() []struct {
	Ctx   context.Context
	Limit int64
} {
	var calls []struct {
		Ctx   context.Context
		Limit int64
	}
	mock.lockGetPendingReminders.RLock()
	calls = mock.calls.GetPendingReminders
	mock.lockGetPendingReminders.RUnlock()
	return calls
}

// ResetGetPendingRemindersCalls reset all the calls that were made to GetPendingReminders.
func (mock *StorageMock) ResetGetPendingRemindersCalls() {
	mock.lockGetPendingReminders.Lock()
	mock.calls.GetPendingReminders = nil
	mock.lockGetPendingReminders.Unlock()
}

// UpdateReminder calls UpdateReminderFunc.
func (mock *StorageMock) UpdateReminder(ctx context.Context, reminder domain.Reminder) error {
	if mock.UpdateReminderFunc == nil {
		panic("StorageMock.UpdateReminderFunc: method is nil but Storage.UpdateReminder was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Reminder domain.Reminder
	}{
		Ctx:      ctx,
		Reminder: reminder,
	}
	mock.lockUpdateReminder.Lock()
	mock.calls.UpdateReminder = append(mock.calls.UpdateReminder, callInfo)
	mock.lockUpdateReminder.Unlock()
	return mock.UpdateReminderFunc(ctx, reminder)
}

// UpdateReminderCalls gets all the calls that were made to UpdateReminder.
// Check the length with:
//
//	len(mockedStorage.UpdateReminderCalls())
func (mock *StorageMock) UpdateReminderCalls() []struct {
	Ctx      context.Context
	Reminder domain.Reminder
} {
	var calls []struct {
		Ctx      context.Context
		Reminder domain.Reminder
	}
	mock.lockUpdateReminder.RLock()
	calls = mock.calls.UpdateReminder
	mock.lockUpdateReminder.RUnlock()
	return calls
}

// ResetUpdateReminderCalls reset all the calls that were made to UpdateReminder.
func (mock *StorageMock) ResetUpdateReminderCalls() {
	mock.lockUpdateReminder.Lock()
	mock.calls.UpdateReminder = nil
	mock.lockUpdateReminder.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *StorageMock) ResetCalls() {
	mock.lockGetPendingReminders.Lock()
	mock.calls.GetPendingReminders = nil
	mock.lockGetPendingReminders.Unlock()

	mock.lockUpdateReminder.Lock()
	mock.calls.UpdateReminder = nil
	mock.lockUpdateReminder.Unlock()
}
