name: build-app
on:
  push:
    branches:
    tags:
    paths_ignored:
      - "**.md"
  pull_request:
    paths_ignored:
      - "**.md"


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: check out code into the Go module directory
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
        id: go

      - name: build
        run: make build
        env:
          TZ: "UTC"

      - name: test
        run: make test
        env:
          TZ: "UTC"
          "CI": "true"

      - name: race test
        run: make race-test
        env:
          TZ: "UTC"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          args: --config=.golangci.yml --sort-results --max-issues-per-linter=1000 --max-same-issues=1000 ./...

      - name: install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=coverage_no_mocks.out
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
