name: build-app
on:
  push:
    branches:
    tags:
    paths_ignored:
      - "**.md"
  pull_request:
    paths_ignored:
      - "**.md"


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: check out code into the Go module directory
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
        id: go

      - name: build
        run: make build
        env:
          TZ: "UTC"

      - name: test
        run: make test
        env:
          TZ: "UTC"
          "CI": "true"

      - name: race test
        run: make race-test
        env:
          TZ: "UTC"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          args: --config=.golangci.yml --sort-results --max-issues-per-linter=1000 --max-same-issues=1000 ./...

      - name: install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=coverage_no_mocks.out
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build and deploy master image to ghcr.io and dockerhub
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.PKG_TOKEN }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          USERNAME: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha}}
          GITHUB_REF: ${{ github.ref}}
        run: |
          ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
          echo GITHUB_REF - $ref
          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
          echo ${DOCKER_HUB_TOKEN} | docker login -u ${USERNAME} --password-stdin
          docker buildx build --push \
              --build-arg CI=github --build-arg GITHUB_SHA=${GITHUB_SHA} --build-arg GIT_BRANCH=${ref} \
              --platform linux/amd64,linux/arm/v7,linux/arm64 \
              -t ghcr.io/${USERNAME}/tg-reminder:${ref} -t ${USERNAME}/tg-reminder:${ref} .

      - name: deploy tagged (latest) to ghcr.io and dockerhub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.PKG_TOKEN }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          USERNAME: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha}}
          GITHUB_REF: ${{ github.ref}}
        run: |
          ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
          echo GITHUB_REF - $ref
          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
          echo ${DOCKER_HUB_TOKEN} | docker login -u ${USERNAME} --password-stdin
          docker buildx build --push \
              --build-arg CI=github --build-arg GITHUB_SHA=${GITHUB_SHA} --build-arg GIT_BRANCH=${ref} \
              --platform linux/amd64,linux/arm/v7,linux/arm64 \
              -t ghcr.io/${USERNAME}/tg-reminder:${ref} -t ghcr.io/${USERNAME}/tg-reminder:latest \
              -t ${USERNAME}/tg-reminder:${ref} -t ${USERNAME}/tg-reminder:latest .
